# Generated by Django 6.0 on 2026-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="youtube_channel_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="youtube_channel_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
