# Generated by Django 6.0 on 2026-04-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_number", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="episodes/"),
                ),
                (
                    "story_summary",
                    models.TextField(
                        blank=True, help_text="Summary of this episode events"
                    ),
                ),
                (
                    "cliffhanger",
                    models.TextField(
                        blank=True, help_text="Ending hook for next episode"
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=30)),
                ("current_scene", models.IntegerField(default=0)),
                ("total_scenes", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Episode",
                "verbose_name_plural": "Episodes",
                "ordering": ["series", "episode_number"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("thriller", "Thriller"),
                            ("sci_fi", "Sci-Fi"),
                            ("horror", "Horror"),
                            ("kids_animation", "Kids Animation"),
                            ("fairy_tale", "Fairy Tale"),
                            ("educational", "Educational"),
                            ("romantic", "Romantic"),
                            ("romantic_comedy", "Romantic Comedy"),
                            ("drama", "Drama"),
                            ("historical", "Historical"),
                            ("mystery", "Mystery"),
                            ("adventure", "Adventure"),
                            ("comedy", "Comedy"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("script", models.TextField(blank=True, help_text="Full JSON script")),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="movies/"),
                ),
                ("duration_minutes", models.IntegerField(default=30)),
                ("total_scenes", models.IntegerField(default=60)),
                (
                    "current_scene",
                    models.IntegerField(
                        default=0, help_text="Current scene being processed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene_number", models.IntegerField()),
                (
                    "description",
                    models.TextField(
                        help_text="Visual description for image generation"
                    ),
                ),
                ("narration", models.TextField(help_text="Text for voiceover")),
                ("image_path", models.CharField(blank=True, max_length=500)),
                ("audio_path", models.CharField(blank=True, max_length=500)),
                ("clip_path", models.CharField(blank=True, max_length=500)),
                ("duration_seconds", models.IntegerField(default=30)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="movies.episode",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scene",
                "verbose_name_plural": "Scenes",
                "ordering": ["movie", "episode", "scene_number"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("thriller", "Thriller"),
                            ("sci_fi", "Sci-Fi"),
                            ("horror", "Horror"),
                            ("kids_animation", "Kids Animation"),
                            ("fairy_tale", "Fairy Tale"),
                            ("educational", "Educational"),
                            ("romantic", "Romantic"),
                            ("romantic_comedy", "Romantic Comedy"),
                            ("drama", "Drama"),
                            ("historical", "Historical"),
                            ("mystery", "Mystery"),
                            ("adventure", "Adventure"),
                            ("comedy", "Comedy"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Series premise and main characters"),
                ),
                ("total_episodes", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Series",
                "verbose_name_plural": "Series",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="episode",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="movies.series",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={("series", "episode_number")},
        ),
    ]
