# Generated by Django 6.0 on 2026-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="youtube_id",
            field=models.CharField(
                blank=True, help_text="YouTube Video ID", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="youtube_id",
            field=models.CharField(
                blank=True, help_text="YouTube Video ID", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
